/*
 
 */
package multiply;

import java.util.Random;
import java.util.Scanner;

public class Multiply {
    
    // variables
    boolean userAnswer;
    int userInput;
    int firstRandomNum;
    int secondRandomNum;
    int questionsAsked = 0;
    int correctAnswers = 0;
    int[][] responseStorage = new int[5][100];
    int row = 0;
    int col = 0;
   
    public void quiz(){
        
        do{
            createQuestion();
            getUserInput();
            checkResponse(userInput);
        }while( userInput != -1);
   
    }
    
    // creates a question and gets the users input
    public void createQuestion(){
        
        // It generates a new multiplication question
        Random randNum = new Random();
    
        // generate 2 positive random numbers 
        firstRandomNum = randNum.nextInt(9);
        
        // store the generated number
        responseStorage[row][col] = firstRandomNum;
        col = col + 1;
        
        secondRandomNum = randNum.nextInt(9);
        responseStorage[row][col] = secondRandomNum;
        col = col + 1;
        
        // ask the user for an answer
        System.out.printf("How much is %d times %d? \n", firstRandomNum, secondRandomNum);
        System.out.println("Enter your answer(-1 to exit):");
      
    }
    
    
    // get user input
    public void getUserInput(){
     
        Scanner in = new Scanner(System.in);
        userInput = in.nextInt();
        if (userInput != -1){
            questionsAsked ++;
        }
        responseStorage[row][col] = userInput;
            col = col + 1;
        
    }
    
    
    // check if the user anwered correct 
    public void checkResponse(int input){
        
        if (userInput == -1){
            printQuestionResult();
        }  
        else if (input == firstRandomNum * secondRandomNum ){
            userAnswer = true;
            correctAnswers ++;
        }
        else{
            userAnswer = false;
        }
        System.out.println(createResponce(userAnswer));
        System.out.println("");
    }
    
   
    // returns an answer to the question
    public String createResponce(boolean correct){
        
        // create a random number to display randome messages
        Random randNum = new Random();
        int listIndex = randNum.nextInt(4);
        
        // correct answer messages
        String[] correctAnswer = 
            {"Very good!", "Excellent!", "Nice work!", 
            "Keep up the good work!"};
        
        // wrong answer messages
        String[] wrongAnswer = 
            {"No. Please try again.", "Wrong. Try once more.", 
            "Don\'t give up!", "No. Keep trying"};
        
        if(correct){
            return correctAnswer[listIndex];
        }
        else{
            return wrongAnswer[listIndex];
        }
    }
    
    
    public void printQuestionResult (){
        System.out.print("The questions generated by the system are: ");
        
        for(int i = 0; i < questionsAsked * 3; i+=3){
            System.out.printf("\n%d * %d = %d ", responseStorage[0][i], responseStorage[0][i + 1], responseStorage[0][i] * responseStorage[0][i + 1]);
            
            if (responseStorage[0][i + 2] !=  responseStorage[0][i] * responseStorage[0][i + 1]){
                System.out.printf("Your answer was %d, ", responseStorage[0][i + 2]);
                System.out.print("which is incorrect.");
            }   
        }
           
        System.out.println("\n----------------------------------------------------------------------------------");
        System.out.printf("You got %d questions and made %d questions correct \n", questionsAsked, correctAnswers);
//        if(correctAnswers > questionsAsked ){
//            System.out.println(createResponce(true));
//        }
//        else{
//            System.out.println(createResponce(false));
//        }
    }
}
